### ISSUE TITLE
Licence Question

### ISSUE THREAD

**Issue by JustSomeRandomUser** [DaZombieKiller/VHacdSharp#3]
Hi Benjamin Moir,
i would like to use this vhacd library inside my own project but i cant find the licence file.
Is it possible that you add a licence to the repository or that you can tell me if I'm allowed to use it for commercial purposes?

Thank you.

**Comment by DaZombieKiller** [comment]
@JustSomeRandomUser 
Hi, sorry I took so long to respond to this!

I currently don't consider this C# binding finished enough to be "ready for use", so I haven't formally set up the repository with a license and readme yet.

That said, VHacdSharp is licensed under the same license as V-HACD itself: the BSD 3-clause license. So yes, you can use it for commercial purposes. I'll add a license file right now to clear things up a little.

**Comment by DaZombieKiller** [comment]
Solved in 10b7ef1953745b5445f524d04655de32b3d2b964.
